# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f681db26893e7563e5a7af0aa6dc91081b556fef7531f00c5a6a1f88fadd868976a1f09e2e15823ba68d313af42ca72f6b186ac13d6e045537eeefe44cb1637

test:
  secret_key_base: beeb92002358dd32518d34eb8912920390b144d974b82263cdc9d019646a3a792f18b1c1868a244641ce115ceeb128067082efee2226d15e93add8dc9d056e77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
